name: ci-multi-version

on: 
  pull_request:
    branches: 
      - develop

jobs: 
  check-application:
    strategy:
      matrix:
        version: [1.14, 1.15]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.version }}
      - run: go test
      - run: go run math.go